# Generated by Django 3.2.24 on 2026-03-22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0162_add_notification_timestamps_20251217_0055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("input_question", "Input Question"),
                    ("multiple_selection", "Multiple Selection"),
                    ("single_selection", "Single Selection"),
                    ("free_response", "Free Response"),
                    ("perseus_question", "Perseus Question"),
                    ("true_false", "True/False"),
                    ("ordering", "Ordering"),
                ],
                default="multiple_selection",
                max_length=50,
            ),
        ),
    ]
